### ISSUE TITLE
new plaftorm for pine map

### ISSUE THREAD

**Issue by stefanocudini** [Istador/pine-interactive-map#29]
hi
you would probably be interested in building a new map with a much higher level of user interaction!
This I could do by combining the work you have done on this map by connecting the data and using a new platform designed specifically for geosocial networks and/or web games like these.

[KeplerJs.io](https://keplerjs.io/)

it's open source and you can use it as much as you want;)

in addition to the official demo(https://demo.keplerjs.io/) you can find one of the first applications created with kepler online here, a climbers social network
[climbing.social](https://climbing.social/)

**Comment by Istador** [comment]
At this point in time, I don't see much use of that. In the beginning of the project, when the game was still in beta, and we didn't extract coordinates directly from the game files (see issues 6 and 17), but wrote them down manually and shared them using a google spreadsheet, a community integration for the map would have been really helpful.

But now the map contains all collectibles and resources that exist in the game, without much need to add more. According to the game developers, it's unlikely that there will be many additions to the game apart from bug fixes. It's not like earth which is extremely big, with ongoing life that changes things up all the time and with 7 billion people on it. But it's a small virtual area with a limited amount of data needed.

The only kind of social aspect of the map currently has is its integration with the [game's wiki](https://pine.gamepedia.com/). It links to the wiki pages and the wiki links back to the map (everyone can link to things on the map, see issue 18). If there's any discussion needed for things on the map, e.g. for a specific item, usually there's a page on the wiki for that. Most of the resource places in the game aren't even worth any discussion at all. If there's a need for more information for a specific POI on the map, that can be added to the description using the wiki. The map uses one table on a specific article as the main data source (with page protected to avoid abuse).

Requiring an user account to contribute is something that I dislike even now with the wiki, though some protection is necessary which was the main reason for the change from the publicly writable spreadsheet to the wiki (and also a better history of changes of the data, see issue 4).

Currently I only host static files for the map myself (mostly js files). The map tiles are served via the `raw.githubusercontent.com` CDN, because routing to my one home server is way too slow for the international users of the map (~100 per day). I'm not interested in hosting any database, user accounts and credentials, or dynamic content for this project. Theoretically everyone is able to host the static files and the tiles on their own server and switch to another wiki (or back to a google spreadsheet - the code for that still exists) by changing a few environment variables and rebuilding it (a local file based data source might be a good alternative for the future). The way it is might be useful in the event that I die and can't host the map anymore. Adding additional software and running it for social interactions creates an dependency that complicates things, as you don't want to lose that data.
